version: "3.5"

services:
  host-system-monitor:
    restart: always
    build: .
    ports:
    - "8000:8000"

    networks:
      - basicsetup_some-net
networks:
  basicsetup_some-net:
    external: true